import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import InnerContextProvider from "@/src/providers/InnerContextProvider";
import Navbar from "@/src/components/app/navbar/Navbar";
import SideNav from "@/src/components/app/navbar/SideNav";
import Toast from "@/src/components/common/toast/Toast";
import "./globals.css";

const fontHeader = Exo_2({
  subsets: ["latin"],
  variable: "--font-header",
});

const fontBody = Exo_2({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${fontHeader.variable} ${fontBody.variable}`}>
        <NextTopLoader
          color={""}
          initialPosition={0.85}
          showSpinner={false}
          height={2}
        />
        <InnerContextProvider>
          <Navbar />
          <SideNav />
          {children}
          <Toast />
        </InnerContextProvider>
      </body>
    </html>
  );
}
